extends Node3D

## Runtime helper that builds collision for scanned scene mesh entities.
const WIREFRAME_MATERIAL: Material = preload("res://Art/Materials/M_Hand_Transy.tres")

@onready var static_body: StaticBody3D = $StaticBody3D

var mesh_instance: MeshInstance3D


## Creates and attaches collision generated by OpenXR scene understanding.
func setup_scene(entity: OpenXRFbSpatialEntity) -> void:
    var collision_shape = entity.create_collision_shape()
    if collision_shape:
        static_body.add_child(collision_shape)
